source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AKStompClient_Example', :exclusive => true do
  pod "AKStompClient", :path => "../"
end

target 'AKStompClient_Tests', :exclusive => true do
  pod "AKStompClient", :path => "../"

  
end
